- .travis.yml
- README.md
- lib/api.js
- lib/collection-item.js
- lib/collection.js
- lib/event.js
- lib/method.js
- package.json
Discovered here: https://github.com/desktop/desktop/pull/217
> add node 4 support and travis

- lib/collection-item.js
- test/index.js
Fixes https://github.com/zeke/electron-docs-linter/issues/15
Fixes https://github.com/zeke/electron-docs-linter/issues/8
> Parse enum values

- cli.js
- index.js
- package.json
- test/cli.js
This PR cleans up the CLI a bit and adds a mocha test to ensure it's producing a JSON schema file.
cc @kevinsawicki @jlord
> CLI improvements

- lib/api.js
- lib/collection.js
- lib/property.js
- test/index.js
Fixes #2 
Getting close the MVP!
@kevinsawicki @jlord
> parse instance properties

- README.md
> update CLI docs, description, and deps list in readme

- cli.js
- lib/collection-item.js
- lib/method.js
- test/index.js
Fixes https://github.com/zeke/electron-docs-linter/issues/25
> Verify that all method parameters are documented

- lib/api.js
- test/cli.js
- test/index.js
> Static Methods

- README.md
- lib/collection-item.js
- lib/event.js
- lib/method.js
- test/index.js
> rename arguments to parameters

- lib/api.js
- test/index.js
> Descriptions

- lib/api.js
- lib/seeds.js
- test/cli.js
- test/index.js
BrowserWindow: win
NativeImage: image
etc
> give every class an example instance name

- lib/api.js
- lib/collection-item.js
- lib/parsers.js
- test/index.js
Fixes https://github.com/zeke/electron-docs-linter/issues/12
> Constructors

- lib/api.js
> use slug to generate dom id

- README.md
https://github.com/electron/electron-docs-linter/commit/6bfe579781031dce72dc8deb715d7e48c6a6e6d7#commitcomment-19150611
Thanks, @hokein
> fix heading in readme

- lib/parsers.js
- test/index.js
Fixes #46 
Hoping to land this before 1.4.2 is released.
> allow parameter descriptions to span multiple lines

- lib/parsers.js
- package.json
- test/index.js
> Decode HTML entities in descriptions

- .gitignore
- lib/collection-item.js
- lib/method.js
- lib/parsers.js
- test/errors.js
- test/fixtures/malformed/web-frame.md
- test/index.js
Pairs with https://github.com/electron/electron/pull/7339
> Parse return values from docs when available

- .gitignore
- lib/parsers.js
- package.json
- test/index.js
@MarshallOfSound found this ✨ 🐞 ✨
> Avoid deep property parsing

- lib/parsers.js
- test/index.js
> Allow return value types to be inside links

- index.js
- lib/api.js
- lib/parsers.js
- lib/schema.js
- lib/seeds.js
- package.json
- test/cli.js
- test/fixtures/malformed/structures/bounds.md
- test/fixtures/malformed/structures/certificate.md
- test/fixtures/malformed/structures/display.md
- test/fixtures/malformed/structures/jump-list-category.md
- test/fixtures/malformed/structures/jump-list-item.md
- test/fixtures/malformed/structures/memory-usage-details.md
- test/fixtures/malformed/structures/shortcut-details.md
- test/fixtures/malformed/structures/task.md
- test/fixtures/malformed/structures/thumbar-button.md
- test/index.js
🔗 https://github.com/electron/electron/pull/7379
/cc @zeke 
Requires the changes to `electron-docs` for the structures markdown to be sent through
> Initial parsing of structures

- lib/parsers.js
- test/cli.js
- test/errors.js
- test/index.js
Parse the function parameters that have been specified in electron/electron/pull/7596
/cc @zeke
> Output function params

- lib/api.js
- lib/seeds.js
- test/fixtures/malformed/net.md
- test/index.js
> Add the new net module to the seeds

- package.json
> update clean-deep with fix for recursive array cleaning

- package.json
> oops electron-docs is a runtime dep

- package.json
https://github.com/electron/electron-docs/pull/4
> update electron-docs to fix windows path issue

- lib/parsers.js
- test/index.js
Motivated to wrap this up after @deed02392 helped us out with https://github.com/electron/electron/pull/8009/files
Fixes #42
cc @enlight @MarshallOfSound
> add `required` boolean property to parameters

- lib/method.js
- lib/parsers.js
- lib/property.js
- test/index.js
Fixes #82
Note this is a breaking change so if we're doing semver we should probably major
> Parse array types as singular types and mark them as collections

- index.js
- lib/api.js
- lib/collection.js
- lib/parsers.js
- lib/property.js
- test/fixtures/electron/docs/api/touch-bar.md
- test/index.js
Fixes some issues with the TB doc enums not having descriptions 👍 
/cc @zeke
> Enums don't need a description + more changes

- lib/parsers.js
Squashing all the 🐛 
/cc @zeke
> Handle sanitizing an undefined description

- lib/api.js
> Support webview events

- lib/parsers.js
- test/index.js
> Include code in description

- lib/parsers.js
- test/fixtures/electron/docs/api/session.md
- test/index.js
As in the title 😆 
Required for electron/electron#11059
/cc @zeke
> Get props params for multitype
